# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arlmaster/fastica

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arlmaster/fastica

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arlmaster/fastica/CMakeFiles /home/arlmaster/fastica/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arlmaster/fastica/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named icalib

# Build rule for target.
icalib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icalib
.PHONY : icalib

# fast build rule for target.
icalib/fast:
	$(MAKE) -f CMakeFiles/icalib.dir/build.make CMakeFiles/icalib.dir/build
.PHONY : icalib/fast

#=============================================================================
# Target rules for targets named recursiveica

# Build rule for target.
recursiveica: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recursiveica
.PHONY : recursiveica

# fast build rule for target.
recursiveica/fast:
	$(MAKE) -f CMakeFiles/recursiveica.dir/build.make CMakeFiles/recursiveica.dir/build
.PHONY : recursiveica/fast

src/recursiveica.o: src/recursiveica.cpp.o
.PHONY : src/recursiveica.o

# target to build an object file
src/recursiveica.cpp.o:
	$(MAKE) -f CMakeFiles/recursiveica.dir/build.make CMakeFiles/recursiveica.dir/src/recursiveica.cpp.o
.PHONY : src/recursiveica.cpp.o

src/recursiveica.i: src/recursiveica.cpp.i
.PHONY : src/recursiveica.i

# target to preprocess a source file
src/recursiveica.cpp.i:
	$(MAKE) -f CMakeFiles/recursiveica.dir/build.make CMakeFiles/recursiveica.dir/src/recursiveica.cpp.i
.PHONY : src/recursiveica.cpp.i

src/recursiveica.s: src/recursiveica.cpp.s
.PHONY : src/recursiveica.s

# target to generate assembly for a file
src/recursiveica.cpp.s:
	$(MAKE) -f CMakeFiles/recursiveica.dir/build.make CMakeFiles/recursiveica.dir/src/recursiveica.cpp.s
.PHONY : src/recursiveica.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... icalib"
	@echo "... rebuild_cache"
	@echo "... recursiveica"
	@echo "... src/recursiveica.o"
	@echo "... src/recursiveica.i"
	@echo "... src/recursiveica.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

